# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=100)),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bibliotecas', models.ManyToManyField(to='Biblioteca.Biblioteca')),
            ],
        ),
    ]
